import time
import pyautogui





time.sleep(10)


pyautogui.write("Michel Goulet")
pyautogui.press('enter')
pyautogui.write("Software Developer")
pyautogui.press('enter')
pyautogui.write("78000")
pyautogui.press('enter')
pyautogui.write("3000")
pyautogui.press('enter')
pyautogui.write("2000")
pyautogui.press('enter')

pyautogui.write("Maryam Barakat")
pyautogui.press('enter')
pyautogui.write("Project Manager")
pyautogui.press('enter')
pyautogui.write("110000")
pyautogui.press('enter')
pyautogui.write("4000")
pyautogui.press('enter')
pyautogui.write("4000")
pyautogui.press('enter')

pyautogui.write("Mark Crawford")
pyautogui.press('enter')
pyautogui.write("Senior Design Engineer")
pyautogui.press('enter')
pyautogui.write("97000")
pyautogui.press('enter')
pyautogui.write("5000")
pyautogui.press('enter')
pyautogui.write("3000")
pyautogui.press('enter')

pyautogui.write("Rakesh Patel")
pyautogui.press('enter')
pyautogui.write("Chief Technology Officer")
pyautogui.press('enter')
pyautogui.write("900000")
pyautogui.press('enter')
pyautogui.write("1200000")
pyautogui.press('enter')
pyautogui.write("45000")
pyautogui.press('enter')


pyautogui.write("Christopher Smith")
pyautogui.press('enter')
pyautogui.write("Vice President")
pyautogui.press('enter')
pyautogui.write("500000")
pyautogui.press('enter')
pyautogui.write("100000")
pyautogui.press('enter')
pyautogui.write("33000")
pyautogui.press('enter')

pyautogui.write("Anna Pawlowska")
pyautogui.press('enter')
pyautogui.write("President")
pyautogui.press('enter')
pyautogui.write("3000000")
pyautogui.press('enter')
pyautogui.write("900000")
pyautogui.press('enter')
pyautogui.write("160000")
pyautogui.press('enter')

pyautogui.write("Christopher Smith")
pyautogui.press('enter')

time.sleep(2)

pyautogui.write("Taha Ali")
pyautogui.press('enter')
pyautogui.write("Senior Test Engineer")
pyautogui.press('enter')
pyautogui.write("88000")
pyautogui.press('enter')
pyautogui.write("1000")
pyautogui.press('enter')
pyautogui.write("900")
pyautogui.press('enter')

pyautogui.write("Parissa Belfort")
pyautogui.press('enter')
pyautogui.write("Team Lead")
pyautogui.press('enter')
pyautogui.write("100000")
pyautogui.press('enter')
pyautogui.write("5000")
pyautogui.press('enter')
pyautogui.write("6000")
pyautogui.press('enter')

pyautogui.write("Mark Cuban")
pyautogui.press('enter')
pyautogui.write("Owner")
pyautogui.press('enter')
pyautogui.write("3000000")
pyautogui.press('enter')
pyautogui.write("3000000")
pyautogui.press('enter')
pyautogui.write("1000000")
pyautogui.press('enter')

pyautogui.write("Trevor Hansen")
pyautogui.press('enter')
pyautogui.write("Senior Vice President")
pyautogui.press('enter')
pyautogui.write("750000")
pyautogui.press('enter')
pyautogui.write("120000")
pyautogui.press('enter')
pyautogui.write("60000")
pyautogui.press('enter')

pyautogui.write("Parissa Belfort")
pyautogui.press('enter')
